daheng_camera:
  ros__parameters:
    width: 1280
    height: 720
    exposure: 10000
    auto_exposure: false
    auto_white_balace: false
    gain: 0
    fps: 100
    rgain: 19.8
    bgain: 19.8
    ggain: 10.0
    time_offset: 0
    auto_exp_change: false
    max_exp: 0
    min_exp: 0